- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    cdwuser: "cdwadmin" 
  tasks: 
    - debug:
        msg: Starting test playbook

    - debug:
        msg: "HOME environment variable is {{ lookup('env','HOME') }}"

    - debug:
        msg: "Morpheus instance hostname is {{ morpheus['instance']['hostname'] }}"

    # Get Morpheus cypher
    - name: get Morpheus secret/provisioning cypher
      set_fact:
        secret: "{{ lookup('cypher','secret=secret/provisioning') }}"
      no_log: true

    # Set variables from Morpheus cypher content
    - name: set values from Morpheus cypher
      set_fact:
        snmpd_username: "{{ secret.linux.snmp.username }}"
        snmpd_password: "{{ secret.linux.snmp.password }}"
      no_log: true

    # Get bmn_tun2_ip
    - name: Get BMN tunnel2 ip from GetTenantDetails task
      set_fact:
        bmn_ip: "{{ morpheus.results.GetTenantDetails.bmn_tun2_ip }}"

    - name: Get password hash temp filename
      set_fact:
         tempfile: "{{ morpheus.results.createlocaladminaccount.temp_hash_file }}"

    - name: Read password hash content
      set_fact:
         password_hash: "{{lookup('file',tempfile)}}" 

    - debug:
       msg: "SHA512 content {{ password_hash }}"

    - name: Create group for cdwadmin user
      group:
        name: "{{ cdwuser }}"
        state: present

    - name: Create the cdw admin user and add it to the cdwadmin group
      user:
        name: "{{ cdwuser }}"
        state: present
        create_home: True
        password: "{{ password_hash }}"
        group: "{{ cdwuser }}"

    - debug:
        msg: Ending test playbook

