- hosts: all
  gather_facts: false
  tasks: 
    - debug:
        msg: Starting test playbook

    - debug:
        msg: "HOME environment variable is {{ lookup('env','HOME') }}"

    - debug:
        msg: "Test simple secret 'mysimplekey' has value {{ lookup('cypher','secret=secret/mysimplekey') }}"

    - debug:
        msg: "Test JSON string val 'mystring' has value {{ lookup('cypher','secret=secret/myjsonobject:mystring') }}"

    - debug:
        msg: "Test JSON integer val 'myinteger' has value {{ lookup('cypher','secret=secret/myjsonobject:myinteger') }}"

    - debug:
        msg: "Test JSON boolean val 'myboolean' has value {{ lookup('cypher','secret=secret/myjsonobject:myboolean') }}"

#    - debug:
#        msg: "Test JSON array val 'mylist[0]' has value {{ lookup('cypher','secret=secret/myjsonobject:mylist[0]') }}"

    - debug:
        msg: "Test JSON object val 'myobject.mypropertykey' has value {{ lookup('cypher','secret=secret/myjsonobject:myobject.mypropertykey') }}"

#    - debug:
#        msg: "CLI extra var myclikey is {{ myclikey }}"

#    - debug:
#        msg: "CLI extra var myclikey2 is {{ myclikey2 }}"


#    - name: ping all hosts
#      ping:

    - debug:
        msg: Ending test playbook

