- hosts: all
  gather_facts: false
  tasks: 
    - debug:
        msg: Starting test playbook

    - debug:
        msg: "Home environment variable is {{ lookup('env','HOME') }}"

    - debug:
        msg: "CLI extra var myclikey is {{ myclikey }}"

    - debug:
        msg: "CLI extra var myclikey2 is {{ myclikey2 }}"


    - name: ping all hosts
      ping:
