- hosts: all
  tasks: 
    - debug:
        msg: Starting test playbook

    - debug:
        msg: "HOME environment variable is {{ lookup('env','HOME') }}"

    - debug:
        msg: "Morpheus instance hostname is {{ morpheus['instance']['hostname'] }}"

    # Get Morpheus cypher
    - name: get Morpheus secret/provisioning cypher
      set_fact:
        secret: "{{ lookup('cypher','secret=secret/provisioning') }}"
      no_log: true

    # Set variables from Morpheus cypher content
    - name: set values from Morpheus cypher
      set_fact:
        snmpd_username: "{{ secret.linux.snmp.username }}"
        snmpd_password: "{{ secret.linux.snmp.password }}"
      no_log: true

    # Get bmn_tun2_ip
    - name: Get BMN tunnel2 ip from GetTenantDetails task
      set_fact:
        bmn_ip: "{{ morpheus.results.GetTenantDetails.bmn_tun2_ip }}"

    # Get encrypted password
    - name: Get encrypted local user password
      set_fact:
        encrypted_password: "{{ morpheus.results.createlocaladminaccount.encrypted_password }}"
      no_log: true


#    - debug:
#        msg: "Test simple secret 'mysimplekey' has value {{ lookup('cypher','secret=secret/mysimplekey') }}"

#    - debug:
#        msg: "Test JSON string val 'mystring' has value {{ lookup('cypher','secret=secret/myjsonobject:mystring') }}"

#    - debug:
#        msg: "Test JSON integer val 'myinteger' has value {{ lookup('cypher','secret=secret/myjsonobject:myinteger') }}"

#    - debug:
#        msg: "Test JSON boolean val 'myboolean' has value {{ lookup('cypher','secret=secret/myjsonobject:myboolean') }}"

#    - debug:
#        msg: "Test JSON array val 'mylist[0]' has value {{ lookup('cypher','secret=secret/myjsonobject:mylist[0]') }}"

#    - debug:
#        msg: "Test JSON object val 'myobject.mypropertykey' has value {{ lookup('cypher','secret=secret/myjsonobject:myobject.mypropertykey') }}"

#    - debug:
#        msg: "Test JSON object 'myobject' has value {{ lookup('cypher','secret=secret/myjsonobject:myobject') }}"

#    - debug:
#        msg: "CLI extra var myclikey is {{ myclikey }}"

#    - debug:
#        msg: "CLI extra var myclikey2 is {{ myclikey2 }}"


#    - name: ping all hosts
#      ping:

    - debug:
        msg: Ending test playbook

